### ISSUE TITLE
How/where is create_symlinks used?

### ISSUE THREAD

**Issue by claflico** [neillturner/puppet-pm2#1]
I don't see anything in the wildurand nodejs repo that uses this line:

nodejs::create_symlinks:  false

I search for create_symlinks in that repo and nothing is found. 

Can you tell me how/where you are using it?

**Comment by neillturner** [comment]
there used to be a parameter as per this commit: 
  https://github.com/willdurand/puppet-nodejs/blob/master/manifests/install.pp
looks like it has been removed so i need to remove from my docs.

**Comment by neillturner** [comment]
removed from docs
