### ISSUE TITLE
Remove auth info from Detailed Usage example

### ISSUE THREAD

**Issue by claflico** [neillturner/puppet-pm2#2]
Some people like myself who are trying to learn puppet & nodejs will likely just copy/paste your examples initially like I did and suddenly they can't install any packages via npm. Might change it to not require auth initially then they can add it later if they like. 

class { 'pm2':
  npm_repository    => "https://registry.npmjs.org",
  npm_auth          => '',
  npm_always_auth   => false,
  pm2_version       => "latest",

**Comment by neillturner** [comment]
sound good just create a pull request with change and i'll update. thanks i appreciate feedback.

**Comment by neillturner** [comment]
changed example. closing
